[book]
title = "Deterministic Engineering Framework"
authors = ["Gerardo Sorchini"]
language = "en"
src = "src"

[build]
build-dir = "book"

[output.html]
git-repository-url = "https://github.com/discofocx/unified-git-workflow"
